# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: https://bitbucket.org/delivery_center/dc.apis
# File: google/protobuf/empty.proto

defmodule Google.Protobuf.Empty do
  @moduledoc false
  use Protobuf, syntax: :proto3

  defstruct []
end
