# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: https://bitbucket.org/delivery_center/dc.apis
# File: deliverycenter/logging/integration/v1/metrics.proto

defmodule Logging.Deliverycenter.Integration.V1.WriteMetricsRequest do
  @moduledoc false
  use Protobuf, syntax: :proto3

  @type t :: %__MODULE__{
          correlation_id: String.t(),
          environment: String.t(),
          level: String.t(),
          direction: String.t(),
          source_type: String.t(),
          source_name: String.t(),
          caller: String.t(),
          action: String.t(),
          create_timestamp: Google.Protobuf.Timestamp.t() | nil,
          duration_ms: integer,
          root_resource_type: String.t(),
          ext_root_resource_id: String.t(),
          int_root_resource_id: String.t(),
          child_resource_type: String.t(),
          child_resource_id: String.t(),
          ext_store_id: String.t(),
          int_store_id: String.t(),
          error_code: String.t()
        }
  defstruct [
    :correlation_id,
    :environment,
    :level,
    :direction,
    :source_type,
    :source_name,
    :caller,
    :action,
    :create_timestamp,
    :duration_ms,
    :root_resource_type,
    :ext_root_resource_id,
    :int_root_resource_id,
    :child_resource_type,
    :child_resource_id,
    :ext_store_id,
    :int_store_id,
    :error_code
  ]

  field(:correlation_id, 1, type: :string)
  field(:environment, 2, type: :string)
  field(:level, 3, type: :string)
  field(:direction, 4, type: :string)
  field(:source_type, 5, type: :string)
  field(:source_name, 6, type: :string)
  field(:caller, 7, type: :string)
  field(:action, 8, type: :string)
  field(:create_timestamp, 9, type: Google.Protobuf.Timestamp)
  field(:duration_ms, 10, type: :int32)
  field(:root_resource_type, 11, type: :string)
  field(:ext_root_resource_id, 12, type: :string)
  field(:int_root_resource_id, 13, type: :string)
  field(:child_resource_type, 14, type: :string)
  field(:child_resource_id, 15, type: :string)
  field(:ext_store_id, 16, type: :string)
  field(:int_store_id, 17, type: :string)
  field(:error_code, 18, type: :string)
end

defmodule Logging.Deliverycenter.Integration.V1.MetricsService.Service do
  @moduledoc false
  use GRPC.Service, name: "logging.deliverycenter.integration.v1.MetricsService"

  rpc(
    :WriteMetrics,
    Logging.Deliverycenter.Integration.V1.WriteMetricsRequest,
    Google.Protobuf.Empty
  )
end

defmodule Logging.Deliverycenter.Integration.V1.MetricsService.Stub do
  @moduledoc false
  use GRPC.Stub, service: Logging.Deliverycenter.Integration.V1.MetricsService.Service
end
